post_install() {
      cat << 'EOF'

brush-config installed!

Configs are in /etc/skel → new users get them automatically.

For current user run:
    cp /etc/skel/.brushrc ~/.brushrc && cp /etc/skel/.config/starship.toml ~/.config/starship.toml

Add Brush to the list of valid shells
    echo "/usr/bin/brush" | sudo tee -a /etc/shells

Change your root login shell to Brush
    sudo chsh -s /usr/bin/brush
Change your user login shell to Brush
    sudo chsh -s /usr/bin/brush "$USER"

EOF
}

post_upgrade() {
    post_install
}