name: Build obs-studio

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: archlinux:latest
        options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Build package
        run: |
          pacman -Syu --noconfirm && \
          pacman -S --noconfirm sudo base-devel git \
              ffmpeg pipewire rnnoise pciutils mbedtls vulkan-headers qt6-svg uthash ninja \
              cmake extra-cmake-modules ffnvcodec-headers nlohmann-json simde && \
          cd obs-studio
          export MAKEPKG_CONF=/dev/null
          makepkg --noconfirm --skipinteg
          cp *.pkg.tar.zst ..
      
      - name: Extract package info from PKGBUILD
        id: pkg_info
        run: |
          cd obs-studio

          PKGNAME=$(grep "^pkgname=" PKGBUILD | head -1 | cut -d= -f2 | tr -d ' ')
          PKGVER=$(grep "^pkgver=" PKGBUILD | head -1 | cut -d= -f2 | tr -d ' ')
          PKGREL=$(grep "^pkgrel=" PKGBUILD | head -1 | cut -d= -f2 | tr -d ' ')
          EPOCH=$(grep "^epoch=" PKGBUILD | head -1 | cut -d= -f2 | xargs)

          FULLVER="${EPOCH}:${PKGVER}-${PKGREL}"
          PKGFILE="${PKGNAME}-${EPOCH}:${PKGVER}-${PKGREL}-x86_64.pkg.tar.zst"
          TAGVER="v${EPOCH}_${PKGVER}-${PKGREL}"

          if [[ ! -f "$PKGFILE" ]]; then
            echo "Ошибка: пакет $PKGFILE не найден!"
            ls -la
            exit 1
          fi

          echo "PKGNAME=$PKGNAME" >> $GITHUB_ENV
          echo "FULLVER=$FULLVER" >> $GITHUB_ENV
          echo "PKGFILE=$PKGFILE" >> $GITHUB_ENV
          echo "TAG=$TAGVER" >> $GITHUB_ENV

          echo "Пакет: $PKGFILE"
          echo "Тег: v${PKGVER}-${PKGREL}"

      - name: Create and push Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          TAG="${{ env.TAG }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Тег $TAG уже существует, пропускаем создание."
          else
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          fi

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.PKGNAME }} ${{ env.TAG }}
          files: obs-studio/${{ env.PKGFILE }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
